# filepath: /c:/Users/Hari/Desktop/web_ar/render.yaml
services:
  - type: web
    name: web_ar
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn renewable_energy.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: renewable_energy.settings